
# Needed to run on local git repo
repository: logins/logins.github.io

title: Riccardo Loggini
description: Projects Website
logo: /assets/img/Avatar2019.png

linkedin_username: riccardologgini
linkedin_name: Riccardo Loggini

theme: jekyll-theme-minimal