# Needed to run on local git repo
repository: logins/logins.github.io

title: Riccardo Loggini
subtitle: Projects Website
description: "A collection of posts about my personal projects. Subjects range from Computer Graphics to Artificial Intelligence (AI)."
logo: /assets/img/Avatar2019.png

linkedin_username: riccardologgini
linkedin_name: Riccardo Loggini

theme: jekyll-theme-minimal