
# Needed to run on local git repo
repository: logins/logins.github.io

title: Riccardo Loggini
description: Projects Website
logo: /assets/img/avatar2019_sepia.png


theme: jekyll-theme-minimal